version: "3.9"

services:
  httpd:
    build: ./docker/httpd
    container_name: biblio_httpd
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html

  api:
    build: ./docker/php
    container_name: myapp_api
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html
    expose:
      - "9000"

  db:
    image: postgres:16
    container_name: biblio_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build: ./docker/node
    container_name: biblio_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

volumes:
  db-data: